# Generated by Django 4.2.7 on 2023-12-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('UserName', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=10)),
                ('CPassword', models.CharField(max_length=10)),
                ('EmailId', models.EmailField(max_length=254)),
                ('MobileNo', models.IntegerField()),
            ],
        ),
    ]
